kind: pipeline
type: docker
name: build

steps:
  - name: restore-cache
    image: meltwater/drone-cache:dev
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      PLUGIN_PATH_STYLE: true
      PLUGIN_BUCKET: "drone"
      PLUGIN_ENDPOINT: http://10.200.0.16:9000
      PLUGIN_REGION: 'default'
    pull: true
    settings:
      restore: true
      cache_key: "wolfpackmaker"
      archive_format: "gzip"
      mount:
        - 'wolfpackmaker_build'
  
  - name: build
    image: python:latest
    pull: true
    commands:
      - pip install virtualenv
      - virtualenv wolfpackmaker_build
      - export VIRTUAL_ENV=/drone/src/wolfpackmaker_build
      - export PATH="$VIRTUAL_ENV/bin:$PATH"
      - pip install -r requirements.txt
      - pip install git+https://git.kalka.io/kalka/packmaker.git
      - pyinstaller wolfpackmaker.py -y

  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      PLUGIN_PATH_STYLE: true
      PLUGIN_BUCKET: "drone"
      PLUGIN_ENDPOINT: http://10.200.0.16:9000
      PLUGIN_REGION: 'default'
    pull: true
    settings:
      rebuild: true
      cache_key: "wolfpackmaker"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - 'wolfpackmaker_build'