kind: pipeline
type: docker
name: build

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache:dev
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "wolfpackmaker"
      archive_format: "gzip"
      mount:
        - '/drone/src/wolfpackmaker_build'
  
  - name: build
    image: python:latest
    pull: true
    commands:
      - pip install virtualenv
      - virtualenv wolfpackmaker_build
      - export VIRTUAL_ENV=/drone/src/wolfpackmaker_build
      - pip install -r requirements.txt
      - pip install git+https://git.kalka.io/kalka/packmaker.git
      - pyinstaller wolfpackmaker.py -y

  - name: rebuild-cache-with-filesystem
    image: meltwater/drone-cache:dev
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "wolfpackmaker"
      archive_format: "gzip"
      # filesystem_cache_root: "/tmp/cache"
      mount:
        - '/drone/src/wolfpackmaker_build'