
name: wolfpackmaker-ci

on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted

    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v2
      - run: pacman -Syyu --noconfirm python3
      - run: pip install -r requirements.txt
      - run: python util/curseforgedb.py
      - run: python util/lock.py -m tests/manifest-fabric.yml
      - run: python util/lock.py -m tests/manifest-forge.yml

  docker-build:
    runs-on: self-hosted

    steps:
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/metadata-action
        with:
          images: kalka/wolfpackmaker
      - uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}