
name: wolfpackmaker-ci

on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python3 -m ensurepip
      - run: python3 -m pip install -r requirements.txt
      - run: python3 util/curseforgedb.py
      - run: python3 util/lock.py -m https://raw.githubusercontent.com/WolfpackMC/Wolfpack-Odin/master/manifest.yml
      - run: python3 util/installer.py
      # - run: python3 util/lock.py -m tests/manifest-fabric.yml
      # - run: python3 util/lock.py -m tests/manifest-forge.yml
      # - run: python3 util/lock.py -m tests/manifest-1.7.10.yml
      # - run: python3 util/lock.py -m tests/manifest-1.16.5.yml

  test-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: 'uname -a'
    - run: 'python -VVVVVVV'

  docker-build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: cat requirements.txt
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: kalka/wolfpackmaker:latest